#!/usr/bin/with-contenv bash

#/usr/local/openvpn_as/scripts/openvpnas --nodaemon --umask=0077 --pidfile=/openvpn/pid/openvpn.pid --logfile=/config/log/openvpn.log
/usr/sbin/openvpn \
  --dev tun \
  --daemon ovpn \
  --cd /config/server/ \
  --config $proto.conf \
  --port $port