#!/usr/bin/with-contenv bash


# check Certificates
if [[ ! -d /config/easy-rsa/ ]]; then
  easy_rsa_url='https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.7/EasyRSA-3.0.7.tgz'
  wget -O ~/easyrsa.tgz "$easy_rsa_url" 2>/dev/null || curl -Lo ~/easyrsa.tgz "$easy_rsa_url"
  tar xzf ~/easyrsa.tgz -C ~/ && \
  mv ~/EasyRSA-3.0.7/ /config && \
  mv /config/EasyRSA-3.0.7/ /config/easy-rsa/ && \
  rm -f ~/easyrsa.tgz && \
  chmod -R 755 /config/easy-rsa/
fi


# ca
if [[ ! -e /config/cert/done ]]; then
  rm -f /config/client/done
  rm /config/cert -rf
  mkdir -p /config/cert
  cd  /config/easy-rsa/
  # Create the PKI, set up the CA and the server and client certificates
	./easyrsa init-pki
	./easyrsa --batch build-ca nopass
	EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-server-full server nopass
	EASYRSA_CERT_EXPIRE=3650 ./easyrsa build-client-full client nopass
	EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl
	# Move the stuff we need
	cp pki/ca.crt pki/private/ca.key pki/issued/server.crt pki/private/server.key pki/crl.pem pki/issued/client.crt pki/private/client.key /config/cert -f
	# Generate key for tls-crypt
	/usr/sbin/openvpn --genkey --secret /config/cert/tc.key
	#generate DH PARAMETER
	/usr/bin/openssl dhparam -out /config/cert/dh.pem 1024

	touch /config/cert/done
fi