#!/usr/bin/with-contenv bash

#create tun device
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

shopt -s extglob

if [[ ! -e /config/server/template.txt ]]; then
  localIP=$(awk 'END{print $1}' /etc/hosts)
  echo "local $localIP
topology subnet
server 10.8.0.0 255.255.255.0
push \"redirect-gateway def1 bypass-dhcp\"
ifconfig-pool-persist ipp.txt
push \"dhcp-option DNS 1.1.1.1\"
push \"dhcp-option DNS 1.0.0.1\"
keepalive 10 120
cipher AES-256-GCM
user abc
group abc
persist-key
persist-tun
status openvpn-status.log
script-security 2
verb 3
ca /config/cert/ca.crt
cert /config/cert/server.crt
key /config/cert/server.key
dh /config/cert/dh.pem
tls-crypt /config/cert/tc.key
crl-verify /config/cert/crl.pem
auth SHA512
" > /config/server/template.txt
fi


#Generate TCP config File
rm -f /config/server/tcp.conf
{
    echo "proto tcp"
    cat /config/server/template.txt
  } > /config/server/tcp.conf

#Generate UDP Config File
rm -f /config/server/udp.conf
{
  echo "proto udp"
  echo "explicit-exit-notify"
  cat /config/server/template.txt
} > /config/server/udp.conf

