#!/usr/bin/with-contenv bash

get_public_ip=$(grep -m 1 -oE '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' <<< "$(wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/" || curl -m 10 -4Ls "http://ip1.dynupdate.no-ip.com/")")

if [[ ! -e /config/client/template.txt ]]; then
  touch /config/client/template.txt
  echo "client
dev tun

remote $get_public_ip $port $proto
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-GCM
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3" > /config/client/template.txt
fi

#Generate Connection file
rm -f /config/client/client-$proto-$port.ovpn
{
  cat /config/client/template.txt
	echo "<ca>"
	cat /config/cert/ca.crt
	echo "</ca>"
	echo "<cert>"
	sed -ne '/BEGIN CERTIFICATE/,$ p' /config/cert/client.crt
	echo "</cert>"
	echo "<key>"
	cat /config/cert/client.key
	echo "</key>"
	echo "<tls-crypt>"
	sed -ne '/BEGIN OpenVPN Static key/,$ p' /config/cert/tc.key
	echo "</tls-crypt>"
} > /config/client/client-$proto-$port.ovpn