#!/usr/bin/with-contenv bash
localIP=$(awk 'END{print $1}' /etc/hosts)

iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $localIP
iptables -I INPUT -p $proto --dport $port -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables-save

net.ipv4.ip_forward=1
echo 1 > /proc/sys/net/ipv4/ip_forward